### ISSUE TITLE
Popup-menus not working on mac

### ISSUE THREAD

**Issue by michab66** [smacklib/dev_smack_swing#12]
See https://github.com/Col-E/Recaf/issues/36

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.border.Border.paintBorder(java.awt.Component, java.awt.Graphics, int, int, int, int)" because the return value of "com.apple.laf.AquaMenuPainter$RecyclableBorder.get()" is null
	at java.desktop/com.apple.laf.AquaMenuPainter.paintSelectedMenuItemBackground(AquaMenuPainter.java:157)
	at java.desktop/com.apple.laf.AquaMenuItemUI.paintBackground(AquaMenuItemUI.java:130)
	at java.desktop/com.apple.laf.AquaMenuPainter.paintMenuItem(AquaMenuPainter.java:186)
	at java.desktop/com.apple.laf.AquaMenuItemUI.paintMenuItem(AquaMenuItemUI.java:103)

**Comment by michab66** [comment]
Mac 2023 does only support the default look-and-feel.  Other's, like metal, result in NPEs in some cases.

So on this platform the l&f is not touched on startup and the configured value is ignored.

This may be refineable in the future.
